// Root build script — embeds Windows icon and generates embedded UI module.

use std::collections::HashMap;
use std::io::Write;
use std::{env, fs, path::PathBuf};

fn main() {
    embed_windows_icon();
    generate_embedded_ui();
}

/// Embed appicon.ico into the Windows executable PE resources.
fn embed_windows_icon() {
    #[cfg(windows)]
    {
        let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
        let icon = manifest_dir.join("appicon.ico");
        if icon.exists() {
            let mut res = winres::WindowsResource::new();
            res.set_icon(icon.to_str().unwrap());
            if let Err(e) = res.compile() {
                println!("cargo:warning=Failed to compile Windows resources: {e}");
            }
        }
    }
}

/// Generate `embedded_ui.rs` containing all React UI assets as embedded byte arrays.
///
/// Scans for a built UI directory (ui-dist/ or src/ui-react/dist/). If found,
/// each file becomes an `include_bytes!()` constant with a lookup table.
/// If no UI directory exists, generates an empty stub so the app can fall back
/// to disk-based serving.
fn generate_embedded_ui() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    // Search for built UI directory
    let candidates = [
        manifest_dir.join("ui-dist"),
        manifest_dir.join("src").join("ui-react").join("dist"),
    ];
    let ui_dir = candidates.iter().find(|d| d.join("index.html").exists());

    let dest = out_dir.join("embedded_ui.rs");
    let mut f = fs::File::create(&dest).expect("Failed to create embedded_ui.rs");

    if let Some(dir) = ui_dir {
        println!("cargo:warning=Embedding UI assets from {}", dir.display());
        write_embedded_module(&mut f, dir);
    } else {
        println!("cargo:warning=No UI directory found — embedded UI will be empty (disk fallback)");
        write_empty_module(&mut f);
    }

    // Rebuild if UI files change
    for candidate in &candidates {
        println!("cargo:rerun-if-changed={}", candidate.display());
    }
}

fn write_embedded_module(f: &mut fs::File, dir: &PathBuf) {
    let mut files: Vec<(String, PathBuf)> = Vec::new();
    let mut index_redirects: HashMap<String, String> = HashMap::new();

    collect_files(dir, dir, &mut files, &mut index_redirects);
    files.sort_by(|a, b| a.0.cmp(&b.0));

    writeln!(f, "// Auto-generated by build.rs — DO NOT EDIT").unwrap();
    writeln!(f, "// Embedded UI assets for single-binary deployment.").unwrap();
    writeln!(f, "// Files: {}", files.len()).unwrap();
    writeln!(f).unwrap();

    // Struct definition
    writeln!(f, "pub struct EmbeddedFile {{").unwrap();
    writeln!(f, "    pub path: &'static str,").unwrap();
    writeln!(f, "    pub data: &'static [u8],").unwrap();
    writeln!(f, "    pub mime_type: &'static str,").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(f).unwrap();

    // File table
    writeln!(f, "pub const FILES: &[EmbeddedFile] = &[").unwrap();
    for (url_path, disk_path) in &files {
        let abs_path = disk_path.to_str().unwrap().replace('\\', "/");
        let mime = guess_mime(url_path);
        writeln!(
            f,
            "    EmbeddedFile {{ path: {url_path:?}, data: include_bytes!({abs_path:?}), mime_type: {mime:?} }},"
        )
        .unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();

    // Index redirects
    writeln!(f, "pub const INDEX_REDIRECTS: &[(&str, &str)] = &[").unwrap();
    for (dir_path, index_path) in &index_redirects {
        writeln!(f, "    ({dir_path:?}, {index_path:?}),").unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();

    // Lookup function
    writeln!(
        f,
        "pub fn lookup(path: &str) -> Option<&'static EmbeddedFile> {{"
    )
    .unwrap();
    writeln!(f, "    // Normalize: ensure path starts with /").unwrap();
    writeln!(f, "    let normalized = if path.starts_with('/') {{ path.to_string() }} else {{ format!(\"/{{}}\", path) }};").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "    // Direct lookup").unwrap();
    writeln!(
        f,
        "    if let Some(file) = FILES.iter().find(|f| f.path == normalized) {{"
    )
    .unwrap();
    writeln!(f, "        return Some(file);").unwrap();
    writeln!(f, "    }}").unwrap();
    writeln!(f).unwrap();
    writeln!(
        f,
        "    // Index redirect lookup (e.g. \"/\" → \"/index.html\")"
    )
    .unwrap();
    writeln!(f, "    let with_slash = if normalized.ends_with('/') {{ normalized.clone() }} else {{ format!(\"{{normalized}}/\") }};").unwrap();
    writeln!(f, "    for &(dir_path, index_path) in INDEX_REDIRECTS {{").unwrap();
    writeln!(f, "        if dir_path == with_slash {{").unwrap();
    writeln!(
        f,
        "            return FILES.iter().find(|f| f.path == index_path);"
    )
    .unwrap();
    writeln!(f, "        }}").unwrap();
    writeln!(f, "    }}").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "    None").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(f).unwrap();

    writeln!(f, "pub fn has_files() -> bool {{ !FILES.is_empty() }}").unwrap();
}

fn write_empty_module(f: &mut fs::File) {
    writeln!(f, "// Auto-generated by build.rs — no UI assets found").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "pub struct EmbeddedFile {{").unwrap();
    writeln!(f, "    pub path: &'static str,").unwrap();
    writeln!(f, "    pub data: &'static [u8],").unwrap();
    writeln!(f, "    pub mime_type: &'static str,").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "pub const FILES: &[EmbeddedFile] = &[];").unwrap();
    writeln!(f, "pub const INDEX_REDIRECTS: &[(&str, &str)] = &[];").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "#[allow(unused)]").unwrap();
    writeln!(
        f,
        "pub fn lookup(_path: &str) -> Option<&'static EmbeddedFile> {{ None }}"
    )
    .unwrap();
    writeln!(f, "pub fn has_files() -> bool {{ false }}").unwrap();
}

fn collect_files(
    base: &PathBuf,
    dir: &PathBuf,
    files: &mut Vec<(String, PathBuf)>,
    index_redirects: &mut HashMap<String, String>,
) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files(base, &path, files, index_redirects);
        } else {
            let relative = path.strip_prefix(base).unwrap();
            let url_path = format!("/{}", relative.to_str().unwrap().replace('\\', "/"));
            files.push((url_path.clone(), path.clone()));

            if relative.file_name().unwrap() == "index.html" {
                let dir_url = if let Some(parent) = relative.parent() {
                    if parent.as_os_str().is_empty() {
                        "/".to_string()
                    } else {
                        format!("/{}/", parent.to_str().unwrap().replace('\\', "/"))
                    }
                } else {
                    "/".to_string()
                };
                index_redirects.insert(dir_url, url_path);
            }
        }
    }
}

fn guess_mime(path: &str) -> &'static str {
    match path.rsplit('.').next() {
        Some("html") => "text/html",
        Some("js") => "application/javascript",
        Some("css") => "text/css",
        Some("json") => "application/json",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("svg") => "image/svg+xml",
        Some("ico") => "image/x-icon",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        Some("ttf") => "font/ttf",
        Some("map") => "application/json",
        _ => "application/octet-stream",
    }
}
