#!/usr/bin/env python3
"""
VFS Header Generator — Embeds a directory of static files into a C++ header.

Based on WebUI's virtual_file_system example (vfs.py).
Generates a header that provides a `vfs()` callback compatible with
webui::window::set_file_handler().

Usage:
    python3 generate_vfs.py <input_directory> <output_header>

Example:
    python3 generate_vfs.py build/ui-dist src/generated/embedded_ui.hpp
"""

import os
import sys


def generate_vfs_header(directory: str, output_header: str) -> None:
    files: list[tuple[str, str]] = []
    index_files: dict[str, str] = {}

    for root, _, filenames in os.walk(directory):
        for filename in filenames:
            filepath = os.path.join(root, filename)
            relative_path = os.path.relpath(filepath, directory)
            # Ensure path starts with /
            relative_path = '/' + relative_path.replace('\\', '/')
            files.append((relative_path, filepath))

            # Track index files for directory redirects (only index.html, not index.css etc.)
            if filename == "index.html":
                dir_path = os.path.dirname(relative_path)
                if dir_path not in index_files:
                    index_files[dir_path] = relative_path

    os.makedirs(os.path.dirname(output_header) or '.', exist_ok=True)

    total_bytes = 0
    for _, filepath in files:
        total_bytes += os.path.getsize(filepath)

    with open(output_header, 'w') as out:
        out.write('// Auto-generated by scripts/generate_vfs.py — DO NOT EDIT\n')
        out.write('// Embeds UI assets for single-binary deployment.\n')
        out.write(f'// Source directory: {directory}\n')
        out.write(f'// Files embedded: {len(files)}\n')
        out.write(f'// Total size: {total_bytes:,} bytes\n\n')
        out.write('#pragma once\n\n')
        out.write('#include <cstring>\n')
        out.write('#include <cstdio>\n')
        out.write('#include <webui.h>\n\n')
        out.write('namespace embedded_ui {\n\n')

        # Emit byte arrays for each file
        for i, (relative_path, filepath) in enumerate(files):
            with open(filepath, 'rb') as f:
                data = f.read()
            out.write(f'// {relative_path} ({len(data):,} bytes)\n')
            out.write(f'static const unsigned char FILE_{i}[] = {{')
            # Write in rows of 20 bytes for readability
            for j, byte in enumerate(data):
                if j % 20 == 0:
                    out.write('\n    ')
                out.write(f'0x{byte:02x},')
            out.write('\n};\n\n')

        # File table
        out.write('struct VirtualFile {\n')
        out.write('    const char* path;\n')
        out.write('    const unsigned char* data;\n')
        out.write('    int length;\n')
        out.write('};\n\n')

        out.write('static const VirtualFile files[] = {\n')
        for i, (relative_path, filepath) in enumerate(files):
            size = os.path.getsize(filepath)
            out.write(f'    {{"{relative_path}", FILE_{i}, {size}}},\n')
        out.write('};\n\n')

        out.write(f'static constexpr int file_count = {len(files)};\n\n')

        # Index file redirect table
        out.write('static const char* index_redirects[] = {\n')
        for dir_path, index_path in index_files.items():
            if dir_path == "/":
                out.write(f'    "/", "{index_path}",\n')
            else:
                out.write(f'    "{dir_path}/", "{index_path}",\n')
        out.write('    nullptr\n')
        out.write('};\n\n')

        # Lookup function
        out.write('static bool lookup(const char* path, const unsigned char** data, int* length) {\n')
        out.write('    for (int i = 0; i < file_count; ++i) {\n')
        out.write('        if (std::strcmp(files[i].path, path) == 0) {\n')
        out.write('            *data = files[i].data;\n')
        out.write('            *length = files[i].length;\n')
        out.write('            return true;\n')
        out.write('        }\n')
        out.write('    }\n')
        out.write('    return false;\n')
        out.write('}\n\n')

        # VFS handler — returns full HTTP response (header + body)
        # This is the callback signature expected by webui::window::set_file_handler()
        out.write('/// WebUI file handler callback. Returns a complete HTTP response\n')
        out.write('/// (headers + body) for embedded files, or nullptr to fall through.\n')
        out.write('static const void* handler(const char* path, int* length) {\n')
        out.write('    const unsigned char* file_data;\n')
        out.write('    int file_length;\n\n')

        # Normalize path: ensure it starts with /
        out.write('    // Normalize path — WebUI may pass "index.html" or "/index.html"\n')
        out.write('    char normalized[1024];\n')
        out.write("    if (path[0] != '/') {\n")
        out.write('        std::snprintf(normalized, sizeof(normalized), "/%s", path);\n')
        out.write('    } else {\n')
        out.write('        std::snprintf(normalized, sizeof(normalized), "%s", path);\n')
        out.write('    }\n\n')

        out.write('    if (lookup(normalized, &file_data, &file_length)) {\n')
        out.write('        const char* content_type = webui_get_mime_type(normalized);\n')
        out.write('        const char* header_fmt = "HTTP/1.1 200 OK\\r\\n"\n')
        out.write('                                 "Content-Type: %s\\r\\n"\n')
        out.write('                                 "Content-Length: %d\\r\\n"\n')
        out.write('                                 "Cache-Control: no-cache\\r\\n\\r\\n";\n')
        out.write('        int header_len = std::snprintf(nullptr, 0, header_fmt, content_type, file_length);\n')
        out.write('        *length = header_len + file_length;\n')
        out.write('        auto* response = static_cast<unsigned char*>(webui_malloc(*length));\n')
        out.write('        std::snprintf(reinterpret_cast<char*>(response), header_len + 1, header_fmt, content_type, file_length);\n')
        out.write('        std::memcpy(response + header_len, file_data, file_length);\n')
        out.write('        return response;\n')
        out.write('    }\n\n')

        # Check for index file mapping (e.g. "/" → serve /index.html content directly)
        out.write('    // Check for index file mapping — serve content directly (no redirect)\n')
        out.write('    char redirect_path[1024];\n')
        out.write('    std::snprintf(redirect_path, sizeof(redirect_path), "%s", normalized);\n')
        out.write('    size_t len = std::strlen(redirect_path);\n')
        out.write("    if (len > 0 && redirect_path[len - 1] != '/') {\n")
        out.write("        redirect_path[len] = '/';\n")
        out.write("        redirect_path[len + 1] = '\\0';\n")
        out.write('    }\n')
        out.write('    for (int i = 0; index_redirects[i] != nullptr; i += 2) {\n')
        out.write('        if (std::strcmp(index_redirects[i], redirect_path) == 0) {\n')
        out.write('            // Serve the index file content directly instead of redirecting\n')
        out.write('            if (lookup(index_redirects[i + 1], &file_data, &file_length)) {\n')
        out.write('                const char* ct = webui_get_mime_type(index_redirects[i + 1]);\n')
        out.write('                const char* hdr = "HTTP/1.1 200 OK\\r\\n"\n')
        out.write('                                  "Content-Type: %s\\r\\n"\n')
        out.write('                                  "Content-Length: %d\\r\\n"\n')
        out.write('                                  "Cache-Control: no-cache\\r\\n\\r\\n";\n')
        out.write('                int hl = std::snprintf(nullptr, 0, hdr, ct, file_length);\n')
        out.write('                *length = hl + file_length;\n')
        out.write('                auto* rsp = static_cast<unsigned char*>(webui_malloc(*length));\n')
        out.write('                std::snprintf(reinterpret_cast<char*>(rsp), hl + 1, hdr, ct, file_length);\n')
        out.write('                std::memcpy(rsp + hl, file_data, file_length);\n')
        out.write('                return rsp;\n')
        out.write('            }\n')
        out.write('        }\n')
        out.write('    }\n\n')

        out.write('    return nullptr;\n')
        out.write('}\n\n')

        out.write('} // namespace embedded_ui\n')

    print(f'[VFS] Generated {output_header}: {len(files)} files, {total_bytes:,} bytes total')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(f'Usage: {sys.argv[0]} <input_directory> <output_header>', file=sys.stderr)
        sys.exit(1)

    generate_vfs_header(sys.argv[1], sys.argv[2])
